version: '3.1'

services:
  mysql:
    image: mysql:5.7.33
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql57
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - vol1:/var/lib/mysql
        
  redis:
    image: redis:5.0.13
    restart: always
    ports:
      - "6379:6379"
  mongo:
    image: mongo:4.4.8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - vol2:/var/lib/mongo
volumes:
  vol1:
  vol2: