
server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms1_customer
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
#  kafka:
#    producer:
#        value-serializar: "org.springframework.kafka.support.serializer.JsonSerializer"
