
server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
