server:
  port: 8182
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manager
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  kafka:
    consumer:
      auto-offset-reset: earliest